include:
  - board: nice_nano
    shield: eyelash_sofle_left
    # v2 정의 파일을 직접 참조하도록 빌드 인자 추가
    cmake-args: -Dboard_revision=2.0.0
  - board: nice_nano
    shield: eyelash_sofle_right
    cmake-args: -Dboard_revision=2.0.0
