include:
  - board: nice_nano
    shield: sofle_left,nice_view_adapter,nice_view
    cmake-args: -Dboard_revision=2.0.0
  - board: nice_nano
    shield: sofle_right,nice_view_adapter,nice_view
    cmake-args: -Dboard_revision=2.0.0
